chunk:
  initial_cost: 1000
  cost_increase: 250
portals:
  North_West_Safe_Haven: "world:-9985.5:79.0:-10020.5"
  North_East_Safe_Haven: "world:8518.5:71.0:-9497.5"
  Central_Safe_Haven: "world:-6.5:63.0:2.5"
  South_West_Safe_Haven: "world:-10001.5:71.0:9996.5"
  South_East_Safe_Haven: "world:10025.5:69.0:10018.5"
spawn: "flatworld:-0.5:10.0:2.5:-180.0:0.0"
database: "dev_chocolate_db"
economy:
  blacklist:
    - "AIR"
    - "BEDROCK"
    - "CAVE_AIR"
    - "FIRE"
    - "ENCHANTED_BOOK"
    - "*HEAD"
    - "*WALL_HEAD"
    - "BARRIER"
    - "SPLASH_POTION"
    - "*STEM"
    - "BEETROOTS"
    - "CARROTS"
    - "POTATOES"
    - "BAMBOO_SAPLING"
    - "*WALL_SIGN"
    - "*SPAWN_EGG"
    - "*WALL_FAN"
    - "*WALL_BANNER"
    - "WALL_TORCH"
    - "LEGACY*"
    - "END_GATEWAY"
    - "END_PORTAL"
    - "NETHER_PORTAL"
    - "WATER"
    - "LAVA"
    - "KNOWLEDGE_BOOK"
    - "WRITTEN_BOOK"
    - "JIGSAW"
    - "COMMAND*"
    - "STRUCTURE*"
    - "POTTED*"